baseURL = "https://report.vinhhaphoi.com/"
relativeURLs = true
canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = "https://github.com/vinhhaphoi/OJT-FALL-25-FCJ-AWS"
  description = "VinhDQSE180012 | OJT_FALL_25 - AWS_FCJ_Internship Program"
  author = "its.vnhdq@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Internship Report"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Vinhhaphoi's Facebook Page"
identifier = "Personal Facebook"
url = "https://www.facebook.com/vinhhaphoi2/"
weight = 20

[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> Trang cá nhân facebook của Vinhhaphoi"
identifier = "Facebook cá nhân"
url = "https://www.facebook.com/vinhhaphoi2/"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
